spring.application.name=spring-boot-project

# MySQL Database Configuration
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/spring-boot-project
spring.datasource.username=root

=======
spring.datasource.url=jdbc:mysql://localhost:3306/spring-boot-project?createDatabaseIfNotExist=true
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update

jwt.signer-key=8642eb70e1b158bb30b63efa72def9ae372866ff3f41f52de67b2e3953f7a418
>>>>>>> 6aed02d (final update)
